version: 2
jobs:
  build:
    working_directory: ~/SEG2105_J.I.Joe_Repository
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "Chippy/build.gradle" }}-{{ checksum  "Chippy/app/build.gradle" }}
      - run:
         name: Chmod permissions  
         command: sudo chmod +x ./Chippy/gradlew
      - run:
          name: Download Dependencies
          command: cd Chippy;./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "Chippy/build.gradle" }}-{{ checksum  "Chippy/app/build.gradle" }}
      - run:
          name: Run UnitTest
          command: cd Chippy;./gradlew test
      - store_artifacts:
          path: Chippy/app/build/outputs/apk/debug/
          destination: apks/
      - store_test_results:
          path: Chippy/app/build/test-results
 